### PR TITLE
add Dockerfile parser

### PR DESCRIPTION
**Pull request by JosiahParry**
Closes https://github.com/ThinkR-open/dockerfiler/issues/5

This PR adds a simple parsing function. It reads a Dockerfile and creates a Dockerfile object from it.

### CODE REVIEW

**Comment by JosiahParry** [comment]
I do not believe that the existing CI failure is do to my proposed changes.

**Comment by JosiahParry** [comment]
Please let me know what is needed to address this PR.

**Comment by JosiahParry** [comment]
Please let me know what is needed for this PR.

**Comment by JosiahParry** [comment]
Hey folks. I'd quite like to use this function and have Dockerfiler as a suggested package. What do I need to do to get this merged in? Thanks :)

**Comment by VincentGuyader** [comment]
thanks a lot, thanks for you patience.

on is way to master :)

**Pull request merged**
